name: CloudNetAPI
version: 2.1
author: Dytanic
website: https://cloudnetservice.eu/
description: CloudNet Interface for the Central server

main: de.dytanic.cloudnet.bridge.BukkitBootstrap

softdepend: [Vault, VaultAPI]

commands:
  cloudserver:
    aliases: ["cs"]
